replace printf with echo

diff --git a/bin/submit_check_result b/bin/submit_check_result
--- a/bin/submit_check_result
+++ b/bin/submit_check_result
@@ -118,10 +118,10 @@ function queue_result() {
 
     if [ -n "$svc_description" ];then
         info "queueing service check results to $file: $hostname $svc_description $return_code $plugin_output $performance_data"
-        /usr/bin/printf "%s\t%s\t%s\t%s|%s\027" "$hostname" "$svc_description" "$return_code" "$plugin_output" "$performance_data" >> $file || error "cannot write results to $file: $!"
+        echo -e "${hostname}\t${svc_description}\t${return_code}\t${plugin_output}|${performance_data}" >> $file || error "cannot write results to $file: $!"
     else
         info "queueing host check results to $file: $hostname $return_code $plugin_output $performance_data"
-        /usr/bin/printf "%s\t%s\t%s|%s\027" "$hostname" "$return_code" "$plugin_output" "$performance_data" >> $file || error "cannot write results to $file: $!"
+        echo -e "${hostname}\t${return_code}\t${plugin_output}|${performance_data}" >> $file || error "cannot write results to $file: $!"
     fi
 }
 
